export const auth='api/auth/' 
export const user='api/user/' 
export const course='api/course/' 
export const notification='api/notification/' 
export const payment='api/payment/' 
export const chat='api/chat/' 